egyedi-program-altgim.pdf: egyedi-program-altgim.tex \
    eloszo.tex \
    mi-az-a-bps.tex \
    mi-a-celunk.tex \
    tarsadalom-vs-egyeni.tex \
    alapelvek.tex \
    emberkep.tex \
    kapcsolodasok.tex \
    pedagogiai-pszichologiai-hatter.tex \
    pedagogiai-modszerek.tex \
    kiemelt-fejlesztesi-teruletek.tex \
    eselyegyenloseg.tex \
    kiemelt-figyelmet-igenylo-gyerekek.tex \
    szemelyreszabott-iskola.tex \
    sajat-celok.tex \
    mentoralas.tex \
    tanulasi-szerzodes.tex \
    tanulo-kozosseg.tex \
    tanari-szerepek.tex \
    modulok.tex \
    portfolio.tex \
    tanev-ritmusa.tex \
    visszajelzes-ertekeles.tex \
    biztonsagos_kornyezet.tex \
    szociokracia.tex \
    governance.tex \
    operator.tex \
    konfliktusok-kezelese.tex \
    minosegbiztositas.tex \
    tanarok.tex \
    felvetel-atvetel.tex \
    hianyzasok.tex \
    ki-viheti-el-a-gyereket.tex \
    sarga-narancs-piros-riasztas.tex \
    nat-celjai.tex \
    tantargyak.tex \
    bizonyitvany-evfolyamok.tex \
    tankonyvek.tex \
    erettsegi.tex \
    szemelyisegfejlesztes.tex \
    mindennapos-testmozgas.tex \
    elsosegely.tex \
    onkentesszolgalat.tex \
    nemzetisegek.tex \
    kornyezeti-neveles.tex \
    tantargyak-altgim.tex \
    pedagogusok.tex \
    epuletek.tex \
    quotes.tex \
    references.bib
	xelatex egyedi-program-altgim
	bibtex egyedi-program-altgim
	xelatex egyedi-program-altgim
